In [1]:
import numpy as np
# from gpbr.mfs.polinomial import calculate_3d_polinomials, MFSPolinomials3D, MfSData, calculate_3d_polinomial_coeeficients
from gpbr.mfs.polinomial import calculate_2d_polinomials, MfSData

In [2]:
N=8

In [3]:
beta = np.ones(N+1)
nu = beta[0]
mfs_data = MfSData(beta,nu)

In [4]:
mfs_data

MfSData(Beta=array([1., 1., 1., 1., 1., 1., 1., 1., 1.]), nu=1.0)

In [5]:
polinomials_data = calculate_2d_polinomials(mfs_data, N)

In [6]:
polinomials_data.A[3]

array([ 1.        , -0.91666667,  0.29166667, -0.02083333,         nan,
               nan,         nan,         nan,         nan])

In [7]:
with np.printoptions(precision=7, suppress=True):
    print(polinomials_data.A)

[[ 1.               nan        nan        nan        nan        nan
         nan        nan        nan]
 [ 1.        -0.5              nan        nan        nan        nan
         nan        nan        nan]
 [ 1.        -0.75       0.125            nan        nan        nan
         nan        nan        nan]
 [ 1.        -0.9166667  0.2916667 -0.0208333        nan        nan
         nan        nan        nan]
 [ 1.        -1.0416667  0.4791667 -0.0625     0.0026042        nan
         nan        nan        nan]
 [ 1.        -1.1416667  0.6791667 -0.1229167  0.0098958 -0.0002604
         nan        nan        nan]
 [ 1.        -1.225      0.8875    -0.2        0.0234375 -0.0011719
   0.0000217        nan        nan]
 [ 1.        -1.2964286  1.1017857 -0.2919643  0.0444196 -0.0031808
   0.0001147 -0.0000016        nan]
 [ 1.        -1.3589286  1.3205357 -0.3973214  0.0737723 -0.0067522
   0.0003565 -0.0000093  0.0000001]]


In [8]:
for v_p in polinomials_data.v_polynomials:
    print(v_p)

1.0
1.0 + 0.0 x
1.0 + 0.0 x + 0.125 x**2
1.0 + 0.0 x + 0.29166667 x**2 + 0.0 x**3
1.0 + 0.0 x + 0.47916667 x**2 + 0.0 x**3 + 0.00260417 x**4
1.0 + 0.0 x + 0.67916667 x**2 + 0.0 x**3 + 0.00989583 x**4 + 0.0 x**5
1.0 + 0.0 x + 0.8875 x**2 + 0.0 x**3 + 0.0234375 x**4 + 0.0 x**5 +
(2.17013889e-05) x**6
1.0 + 0.0 x + 1.10178571 x**2 + 0.0 x**3 + 0.04441964 x**4 + 0.0 x**5 +
0.00011471 x**6 + 0.0 x**7
1.0 + 0.0 x + 1.32053571 x**2 + 0.0 x**3 + 0.07377232 x**4 + 0.0 x**5 +
0.00035652 x**6 + 0.0 x**7 + (9.68812004e-08) x**8


In [9]:
for w_p in polinomials_data.w_polynomials:
    print(w_p)

0.0
0.0 - 0.5 x
0.0 - 0.75 x + 0.0 x**2
0.0 - 0.91666667 x + 0.0 x**2 - 0.02083333 x**3
0.0 - 1.04166667 x + 0.0 x**2 - 0.0625 x**3 + 0.0 x**4
0.0 - 1.14166667 x + 0.0 x**2 - 0.12291667 x**3 + 0.0 x**4 -
0.00026042 x**5
0.0 - 1.225 x + 0.0 x**2 - 0.2 x**3 + 0.0 x**4 - 0.00117187 x**5 +
0.0 x**6
0.0 - 1.29642857 x + 0.0 x**2 - 0.29196429 x**3 + 0.0 x**4 -
0.0031808 x**5 + 0.0 x**6 - (1.55009921e-06) x**7
0.0 - 1.35892857 x + 0.0 x**2 - 0.39732143 x**3 + 0.0 x**4 -
0.00675223 x**5 + 0.0 x**6 - (9.30059524e-06) x**7 + 0.0 x**8


In [ ]:
with np.printoptions(precision=4, suppress=True):
    print(polinomials_data.A)

In [6]:
with np.printoptions(precision=4, suppress=True):
    print(polinomials_data.A)

[[ 1.         nan     nan     nan     nan     nan     nan     nan     nan]
 [ 1.     -0.5        nan     nan     nan     nan     nan     nan     nan]
 [ 1.     -0.75    0.125      nan     nan     nan     nan     nan     nan]
 [ 1.     -0.9167  0.2917 -0.0208     nan     nan     nan     nan     nan]
 [ 1.     -1.0417  0.4792 -0.0625  0.0026     nan     nan     nan     nan]
 [ 1.     -1.1417  0.6792 -0.1229  0.0099 -0.0003     nan     nan     nan]
 [ 1.     -1.225   0.8875 -0.2     0.0234 -0.0012  0.         nan     nan]
 [ 1.     -1.2964  1.1018 -0.292   0.0444 -0.0032  0.0001 -0.         nan]
 [ 1.     -1.3589  1.3205 -0.3973  0.0738 -0.0068  0.0004 -0.      0.    ]]


In [10]:
A = polinomials_data.A
A

array([[ 1.00000000e+00,             nan,             nan,
                    nan,             nan,             nan,
                    nan,             nan,             nan],
       [ 1.00000000e+00, -5.00000000e-01,             nan,
                    nan,             nan,             nan,
                    nan,             nan,             nan],
       [ 1.00000000e+00, -7.50000000e-01,  1.25000000e-01,
                    nan,             nan,             nan,
                    nan,             nan,             nan],
       [ 1.00000000e+00, -9.16666667e-01,  2.91666667e-01,
        -2.08333333e-02,             nan,             nan,
                    nan,             nan,             nan],
       [ 1.00000000e+00, -1.04166667e+00,  4.79166667e-01,
        -6.25000000e-02,  2.60416667e-03,             nan,
                    nan,             nan,             nan],
       [ 1.00000000e+00, -1.14166667e+00,  6.79166667e-01,
        -1.22916667e-01,  9.89583333e-03, -2.604166

In [21]:
arr = A[8,:]
arr

array([ 1.00000000e+00, -1.35892857e+00,  1.32053571e+00, -3.97321429e-01,
        7.37723214e-02, -6.75223214e-03,  3.56522817e-04, -9.30059524e-06,
        9.68812004e-08])

In [22]:
arr[::2]

array([1.00000000e+00, 1.32053571e+00, 7.37723214e-02, 3.56522817e-04,
       9.68812004e-08])

In [23]:
arr[1::2]


array([-1.35892857e+00, -3.97321429e-01, -6.75223214e-03, -9.30059524e-06])

In [7]:
for p in polinomials_data.polinomials:
    print(p)

1.0
1.0 - 0.5 x
1.0 - 0.75 x + 0.125 x**2
1.0 - 0.91666667 x + 0.29166667 x**2 - 0.02083333 x**3
1.0 - 1.04166667 x + 0.47916667 x**2 - 0.0625 x**3 + 0.00260417 x**4
1.0 - 1.14166667 x + 0.67916667 x**2 - 0.12291667 x**3 + 0.00989583 x**4 -
0.00026042 x**5
1.0 - 1.225 x + 0.8875 x**2 - 0.2 x**3 + 0.0234375 x**4 -
0.00117187 x**5 + (2.17013889e-05) x**6
1.0 - 1.29642857 x + 1.10178571 x**2 - 0.29196429 x**3 + 0.04441964 x**4 -
0.0031808 x**5 + 0.00011471 x**6 - (1.55009921e-06) x**7
1.0 - 1.35892857 x + 1.32053571 x**2 - 0.39732143 x**3 + 0.07377232 x**4 -
0.00675223 x**5 + 0.00035652 x**6 - (9.30059524e-06) x**7 +
(9.68812004e-08) x**8


In [8]:
points = np.arange(0, 20)
points

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
for n, polinomial in enumerate(polinomials_data.polinomials):
    v = polinomial(points)
    dv = polinomial.deriv()(points)
    d2v = polinomial.deriv(2)(points)
    right = 0
    for m in range(n):
        right += mfs_data.Beta[n-m]*polinomials_data.polinomials[m](points)
    print(max(d2v - 2*mfs_data.nu*dv - right))

0.0
0.0
-0.25
-0.5833333333333335
-0.958333333333333
-1.3583333333333334
-1.7750000000000004
-2.2035714285714283
-2.641071428571429
