In [1]:
import numpy as np
# from gpbr.mfs.polinomial import calculate_3d_polinomials, MFSPolinomials3D, MfSData, calculate_3d_polinomial_coeeficients
from gpbr.mfs.polinomial import calculate_3d_polinomials, MfSData

In [2]:
N=8

In [3]:
beta = np.ones(N+1)
nu = beta[0]
mfs_data = MfSData(beta,nu)

In [4]:
mfs_data

MfSData(Beta=array([1., 1., 1., 1., 1., 1., 1., 1., 1.]), nu=1.0)

In [5]:
polinomials_data = calculate_3d_polinomials(mfs_data, N)

In [6]:
with np.printoptions(precision=4, suppress=True):
    print(polinomials_data.A)

[[ 1.         nan     nan     nan     nan     nan     nan     nan     nan]
 [ 1.     -0.5        nan     nan     nan     nan     nan     nan     nan]
 [ 1.     -0.875   0.125      nan     nan     nan     nan     nan     nan]
 [ 1.     -1.1875  0.3125 -0.0208     nan     nan     nan     nan     nan]
 [ 1.     -1.4609  0.5391 -0.0677  0.0026     nan     nan     nan     nan]
 [ 1.     -1.707   0.793  -0.1419  0.0104 -0.0003     nan     nan     nan]
 [ 1.     -1.9326  1.0674 -0.2435  0.0257 -0.0012  0.         nan     nan]
 [ 1.     -2.1421  1.3579 -0.3719  0.0505 -0.0035  0.0001 -0.         nan]
 [ 1.     -2.3385  1.6615 -0.5265  0.0863 -0.0078  0.0004 -0.      0.    ]]


In [7]:
for p in polinomials_data.polinomials:
    print(p)

1.0
1.0 - 0.5 x
1.0 - 0.875 x + 0.125 x**2
1.0 - 1.1875 x + 0.3125 x**2 - 0.02083333 x**3
1.0 - 1.4609375 x + 0.5390625 x**2 - 0.06770833 x**3 + 0.00260417 x**4
1.0 - 1.70703125 x + 0.79296875 x**2 - 0.14192708 x**3 + 0.01041667 x**4 -
0.00026042 x**5
1.0 - 1.93261719 x + 1.06738281 x**2 - 0.24348958 x**3 + 0.02571615 x**4 -
0.00123698 x**5 + (2.17013889e-05) x**6
1.0 - 2.14208984 x + 1.35791016 x**2 - 0.37190755 x**3 + 0.05045573 x**4 -
0.00351563 x**5 + 0.00011936 x**6 - (1.55009921e-06) x**7
1.0 - 2.33847046 x + 1.66152954 x**2 - 0.5265096 x**3 + 0.08631388 x**4 -
0.00776774 x**5 + 0.00038384 x**6 - (9.68812004e-06) x**7 +
(9.68812004e-08) x**8


In [8]:
points = np.arange(0, 5)
points

array([0, 1, 2, 3, 4])

In [ ]:
for n, polinomial in enumerate(polinomials_data.polinomials):
    v = polinomial(points)
    dv = polinomial.deriv()(points)
    d2v = polinomial.deriv(2)(points)
    right = 0
    for m in range(n):
        right += mfs_data.Beta[n-m]*polinomials_data.polinomials[m](points)
    right = sum([mfs_data.Beta[n-m]*polinomial_3d(ro, m, coef_data) for m in range(0,n)])

In [7]:

points = [-5,-4,-3,-2,-1,0,1,2,3,4,5]
for n in range(1,N+1):
    for ro in points:
        v = polinomial_3d(ro, n, coef_data)
        dv = dpolinomial_3d(ro, n, coef_data)
        d2v = d2polinomial_3d(ro, n, coef_data)
        right = sum([mfs_data.Beta[n-m]*polinomial_3d(ro, m, coef_data) for m in range(0,n)])
        print(d2v - 2*mfs_data.nu*dv - right)

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
-3.552713678800501e-15
0.0
-1.7763568394002505e-15
-8.881784197001252e-16
0.0
0.0
0.0
0.0
0.0
0.0
-7.105427357601002e-15
0.0
0.0
0.0
0.0
0.0
0.0
-8.326672684688674e-17
-2.220446049250313e-16
-5.551115123125783e-17
-1.1102230246251565e-16
1.4210854715202004e-14
0.0
0.0
3.552713678800501e-15
-1.7763568394002505e-15
0.0
0.0
-2.220446049250313e-16
-6.661338147750939e-16
-8.326672684688674e-16
-1.6653345369377348e-15
2.842170943040401e-14
1.4210854715202004e-14
0.0
7.105427357601002e-15
0.0
0.0
2.220446049250313e-16
-2.7755575615628914e-16
-1.4988010832439613e-15
-1.9567680809018384e-15
-4.85722573273506e-15
0.0
0.0
0.0
0.0
0.0
0.0
2.220446049250313e-16
4.440892098500626e-16
3.885780586188048e-15
3.58046925441613e-15
9.048317650695026e-15


In [11]:
N=8

In [12]:
A = np.empty((N+1,N+1))
A[:] = np.nan
Beta = 1
Nu =1

In [14]:
A

array([[nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan]])

In [15]:
## Fill first column
A[:,0]=1
A

array([[ 1., nan, nan, nan, nan, nan, nan, nan, nan],
       [ 1., nan, nan, nan, nan, nan, nan, nan, nan],
       [ 1., nan, nan, nan, nan, nan, nan, nan, nan],
       [ 1., nan, nan, nan, nan, nan, nan, nan, nan],
       [ 1., nan, nan, nan, nan, nan, nan, nan, nan],
       [ 1., nan, nan, nan, nan, nan, nan, nan, nan],
       [ 1., nan, nan, nan, nan, nan, nan, nan, nan],
       [ 1., nan, nan, nan, nan, nan, nan, nan, nan],
       [ 1., nan, nan, nan, nan, nan, nan, nan, nan]])

In [16]:
## Fill diagonal elements
for n in range(1,N+1):
    A[n,n] = -(Beta*A[n-1,n-1])/(2*Nu*n)
A

array([[ 1.00000000e+00,             nan,             nan,
                    nan,             nan,             nan,
                    nan,             nan,             nan],
       [ 1.00000000e+00, -5.00000000e-01,             nan,
                    nan,             nan,             nan,
                    nan,             nan,             nan],
       [ 1.00000000e+00,             nan,  1.25000000e-01,
                    nan,             nan,             nan,
                    nan,             nan,             nan],
       [ 1.00000000e+00,             nan,             nan,
        -2.08333333e-02,             nan,             nan,
                    nan,             nan,             nan],
       [ 1.00000000e+00,             nan,             nan,
                    nan,  2.60416667e-03,             nan,
                    nan,             nan,             nan],
       [ 1.00000000e+00,             nan,             nan,
                    nan,             nan, -2.604166

In [17]:
with np.printoptions(precision=3, suppress=True):
    print(A)

[[ 1.       nan    nan    nan    nan    nan    nan    nan    nan]
 [ 1.    -0.5      nan    nan    nan    nan    nan    nan    nan]
 [ 1.       nan  0.125    nan    nan    nan    nan    nan    nan]
 [ 1.       nan    nan -0.021    nan    nan    nan    nan    nan]
 [ 1.       nan    nan    nan  0.003    nan    nan    nan    nan]
 [ 1.       nan    nan    nan    nan -0.       nan    nan    nan]
 [ 1.       nan    nan    nan    nan    nan  0.       nan    nan]
 [ 1.       nan    nan    nan    nan    nan    nan -0.       nan]
 [ 1.       nan    nan    nan    nan    nan    nan    nan  0.   ]]


In [18]:
def polinomial(n,k, A):
    res = k*(k+1)*A[n,k+1]
    for m in range(k-1, n): # m = k-1;n-1
        res -=Beta*A[m, k-1]
    res /=(2*Nu*k)
    A[n,k]=res

In [19]:
for n in range(0,N+1):
    for m in range(n,-1, -1):
        if m == 0: # Already filled
            continue
        if n == m: # Already filled
            continue
        print(f'{n}:{m}')
        polinomial(n,m, A)
        print(A)

2:1
[[ 1.00000000e+00             nan             nan             nan
              nan             nan             nan             nan
              nan]
 [ 1.00000000e+00 -5.00000000e-01             nan             nan
              nan             nan             nan             nan
              nan]
 [ 1.00000000e+00 -8.75000000e-01  1.25000000e-01             nan
              nan             nan             nan             nan
              nan]
 [ 1.00000000e+00             nan             nan -2.08333333e-02
              nan             nan             nan             nan
              nan]
 [ 1.00000000e+00             nan             nan             nan
   2.60416667e-03             nan             nan             nan
              nan]
 [ 1.00000000e+00             nan             nan             nan
              nan -2.60416667e-04             nan             nan
              nan]
 [ 1.00000000e+00             nan             nan             nan
              nan       

In [30]:
for n in range(0,N+1):
    for m in range(0,n+1):
        if m == 0: # Already filled
            continue
        if n == m: # Already filled
            continue
        print(f'{n}:{m}')
        polinomial(n,m, A)
        print(A)


2:1
[[ 1.                 nan         nan         nan         nan]
 [ 1.         -0.5                nan         nan         nan]
 [ 1.         -0.875       0.125              nan         nan]
 [ 1.                 nan         nan -0.02083333         nan]
 [ 1.                 nan         nan         nan  0.00260417]]
3:1
[[ 1.                 nan         nan         nan         nan]
 [ 1.         -0.5                nan         nan         nan]
 [ 1.         -0.875       0.125              nan         nan]
 [ 1.                 nan         nan -0.02083333         nan]
 [ 1.                 nan         nan         nan  0.00260417]]
3:2
[[ 1.                 nan         nan         nan         nan]
 [ 1.         -0.5                nan         nan         nan]
 [ 1.         -0.875       0.125              nan         nan]
 [ 1.                 nan  0.3125     -0.02083333         nan]
 [ 1.                 nan         nan         nan  0.00260417]]
4:1
[[ 1.                 nan         na

In [21]:
with np.printoptions(precision=3, suppress=True):
    print(A)

[[ 1.       nan    nan    nan    nan    nan    nan    nan    nan]
 [ 1.    -0.5      nan    nan    nan    nan    nan    nan    nan]
 [ 1.    -0.875  0.125    nan    nan    nan    nan    nan    nan]
 [ 1.    -1.188  0.312 -0.021    nan    nan    nan    nan    nan]
 [ 1.    -1.461  0.539 -0.068  0.003    nan    nan    nan    nan]
 [ 1.    -1.707  0.793 -0.142  0.01  -0.       nan    nan    nan]
 [ 1.    -1.933  1.067 -0.243  0.026 -0.001  0.       nan    nan]
 [ 1.    -2.142  1.358 -0.372  0.05  -0.004  0.    -0.       nan]
 [ 1.    -2.338  1.662 -0.527  0.086 -0.008  0.    -0.     0.   ]]


In [22]:
with np.printoptions(precision=3, suppress=True):
    print(coef_data.A)

[[ 1.       nan    nan    nan    nan    nan    nan    nan    nan]
 [ 1.    -0.5      nan    nan    nan    nan    nan    nan    nan]
 [ 1.    -0.875  0.125    nan    nan    nan    nan    nan    nan]
 [ 1.    -1.188  0.312 -0.021    nan    nan    nan    nan    nan]
 [ 1.    -1.461  0.539 -0.068  0.003    nan    nan    nan    nan]
 [ 1.    -1.707  0.793 -0.142  0.01  -0.       nan    nan    nan]
 [ 1.    -1.933  1.067 -0.243  0.026 -0.001  0.       nan    nan]
 [ 1.    -2.142  1.358 -0.372  0.05  -0.004  0.    -0.       nan]
 [ 1.    -2.338  1.662 -0.527  0.086 -0.008  0.    -0.     0.   ]]


In [24]:
with np.printoptions(precision=3, suppress=True):
    print(coef_data.A-A)

[[ 0. nan nan nan nan nan nan nan nan]
 [ 0.  0. nan nan nan nan nan nan nan]
 [ 0.  0.  0. nan nan nan nan nan nan]
 [ 0.  0.  0.  0. nan nan nan nan nan]
 [ 0.  0.  0.  0.  0. nan nan nan nan]
 [ 0.  0.  0.  0.  0.  0. nan nan nan]
 [ 0.  0.  0.  0.  0.  0.  0. nan nan]
 [ 0.  0.  0.  0.  0.  0.  0.  0. nan]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [ ]:
    # def polinomial_coeffs(n):
    #     coefs = np.zeros(n+1)

In [77]:
N=8

In [78]:
beta = np.ones(N+1)
nu = beta[0]
mfs_data = MfSData(beta,nu)

In [88]:
def polinomial_coeffs(n, diagonal_el, mfs_data):
    coefs = np.empty(n+1)
    coefs[:] = np.nan
    coefs[0]=1
    coefs[n] =diagonal_el
    for k in range(n-1, 0, -1): # 0 element already filled
        res = k*(k+1)*coefs[k+1]
        for m in range(k-1, n): # m = k-1;n-1
            res -=mfs_data.Beta[n-m]*A[m, k-1] # TODO: test beta
        res /=(2*mfs_data.nu*k)
        coefs[k] = res
    return coefs

In [89]:
diagonals = np.empty(N+1)
diagonals[:] = np.nan
diagonals[0] = 1

for n in range(1,N+1):
    diagonals[n] = -(mfs_data.Beta[1]*diagonals[n-1])/(2*mfs_data.nu*n)

In [92]:
A_poly = []
for n in range(N+1):
    A_poly.append(polinomial_coeffs(n, diagonals[n], mfs_data))

In [101]:
for n in range(N+1):
    print(A_poly[n]-A[n,:n+1])

[0.]
[0. 0.]
[0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [84]:
diagonals

array([ 1.00000000e+00, -5.00000000e-01,  1.25000000e-01, -2.08333333e-02,
        2.60416667e-03, -2.60416667e-04,  2.17013889e-05, -1.55009921e-06,
        9.68812004e-08])

In [86]:
A.diagonal() - diagonals

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [83]:
with np.printoptions(precision=3, suppress=True):
    print(A)

[[ 1.       nan    nan    nan    nan    nan    nan    nan    nan]
 [ 1.    -0.5      nan    nan    nan    nan    nan    nan    nan]
 [ 1.    -0.875  0.125    nan    nan    nan    nan    nan    nan]
 [ 1.    -1.188  0.312 -0.021    nan    nan    nan    nan    nan]
 [ 1.    -1.461  0.539 -0.068  0.003    nan    nan    nan    nan]
 [ 1.    -1.707  0.793 -0.142  0.01  -0.       nan    nan    nan]
 [ 1.    -1.933  1.067 -0.243  0.026 -0.001  0.       nan    nan]
 [ 1.    -2.142  1.358 -0.372  0.05  -0.004  0.    -0.       nan]
 [ 1.    -2.338  1.662 -0.527  0.086 -0.008  0.    -0.     0.   ]]


In [82]:
A

array([[ 1.00000000e+00,             nan,             nan,
                    nan,             nan,             nan,
                    nan,             nan,             nan],
       [ 1.00000000e+00, -5.00000000e-01,             nan,
                    nan,             nan,             nan,
                    nan,             nan,             nan],
       [ 1.00000000e+00, -8.75000000e-01,  1.25000000e-01,
                    nan,             nan,             nan,
                    nan,             nan,             nan],
       [ 1.00000000e+00, -1.18750000e+00,  3.12500000e-01,
        -2.08333333e-02,             nan,             nan,
                    nan,             nan,             nan],
       [ 1.00000000e+00, -1.46093750e+00,  5.39062500e-01,
        -6.77083333e-02,  2.60416667e-03,             nan,
                    nan,             nan,             nan],
       [ 1.00000000e+00, -1.70703125e+00,  7.92968750e-01,
        -1.41927083e-01,  1.04166667e-02, -2.604166

In [76]:
n=0
coefs = np.zeros()
coefs

array([], dtype=float64)